/**
 * AI Insights Type Definitions
 * 
 * This module defines types for AI-generated market insights.
 */

/**
 * Market insight generated by AI Engine
 */
export interface MarketInsight {
  id: string;
  symbol: string;
  signal: 'bullish' | 'bearish' | 'neutral';
  confidence: number; // 0-100
  summary: string;
  indicators: {
    rsi?: number;
    volumeChange?: number;
    volatility?: number;
    smaSignal?: 'golden_cross' | 'death_cross' | null;
  };
  timestamp: number;
}

/**
 * Market data input for insights generation
 */
export interface MarketData {
  symbol: string;
  name: string;
  price: number;
  priceHistory: number[]; // Array of historical prices for calculations
  volume24h: number;
  averageVolume: number; // 7-day average volume
  change24h: number;
  high24h: number;
  low24h: number;
}

/**
 * Cached insights entry
 */
export interface CachedInsight {
  insights: MarketInsight[];
  timestamp: number;
}
